### ISSUE TITLE
undefined is not a function (evaluating 'StatusBar.setBarStyle(data.style)')

### ISSUE THREAD

**Issue by iDuuck** [react-native-community/react-native-navbar#157]
Getting this error since today. How to fix this? :)

I am using the following versions:

```
"react-native": "^0.21.0",
"react-native-navbar": "^1.2.2"
```

Update to latest version is not working though.

**Comment by Kureev** [comment]
Not quite sure how that may happen. 
`StatusBar.setBarStyle` is a function in 0.21 ([proof](https://github.com/facebook/react-native/blob/31bb85a210e8a6edba4f59df6eb36ccc5cc58d9e/Libraries/Components/StatusBar/StatusBar.js))

**Comment by iDuuck** [comment]
That's really strange, the error even appears, when removing the props from the `NavigationBar`

**Comment by Kureev** [comment]
Just a suggestion: can you try to `rm -rf node_modules` and install them again?

**Comment by jjluebke** [comment]
Indeed, `StatusBar.setBarStyle` wasn't in [0.21](https://github.com/facebook/react-native/blob/v0.21.0/Libraries/Components/StatusBar/StatusBar.js) but  introduced in [0.22](https://github.com/facebook/react-native/blob/v0.22.0/Libraries/Components/StatusBar/StatusBar.js)

**Comment by iDuuck** [comment]
Still not working for me with a newer version. But I am not working on this
project anymore, so I am not able to test it.![](https://link.nylas.com/open/4
jphnlyqm3wikqu8u00ujlwoe/b5f0d01a16bb4a198a0cc67475aaf96a)

**Comment by damathryx** [comment]
@iDuuck 
hi. i solved this by changing

StatusBar.setBarStyle(data.style);
to 
StatusBar.barStyle = data.style;

in node_modules/react-natinve-navbar/ index.js

might work for you too.

**Comment by Kureev** [comment]
Closed as outdated

**Comment by CLLDesigns** [comment]
Just in case anyone finds this from a Google search; Triple check that you are actually importing StatusBar from 'react-native' and not somewhere else accidentally.
