### ISSUE TITLE
about es6 issue import react-native-navbar

### ISSUE THREAD

**Issue by slowsay** [react-native-community/react-native-navbar#178]
I think about add es6 code write :
## index.js

module.exports =NavigationBar
modify by:
export default NavigationBar

**Comment by ecasilla** [comment]
+1

**Comment by ecasilla** [comment]
This is happening because I'm on the latest version of react native which doesn't support importing React props from react native. You must use react exclusively.

```
import React, {
  Component,
  View,
  Text,
  StyleSheet,
  TouchableHighlight,
  TextInput,
  PropTypes,
} from 'react-native';
```

Needs to be 

```
import React, {Component, PropTypes} from "react";
import {View, Text, StyleSheet, TouchableHighlight, TextInput} from "react-native";
```

**Comment by Kureev** [comment]
I believe this one is not actual anymore. Feel free to ping me if you disagree
