### ISSUE TITLE
Logo instead of title text 

### ISSUE THREAD

**Issue by HubMahesh** [react-native-community/react-native-navbar#187]
Hi There,

How can i use logo (jpg, png or svg) in place of  title text instead of title text. Can i have the solution on this section

**Comment by Kureev** [comment]
You should use custom components. It's described in the README and covered in the [example here](https://github.com/react-native-community/react-native-navbar/blob/master/examples/CustomElements/index.ios.js)

**Comment by HubMahesh** [comment]
Hi @Kureev ,
Thanks, to this post, i can successfully show logo in nav bar. i'have directly to the title.
Thanks
