### ISSUE TITLE
Native transition support

### ISSUE THREAD

**Issue by janroures** [react-native-community/react-native-navbar#190]
Hello, I noticed that the navigator isn't using native transitions. For example, when you push/pop to a new component, the bar doesn't stay fixed and a white background appears behind it. Any information about that?

Thank you.

**Comment by joncursi** [comment]
I believe this library is just straight JS with no native bridge. Check out https://github.com/exponentjs/ex-navigation for native support.

**Comment by Kureev** [comment]
I believe there is a misconception: this component is not supposed to provide you any navigation hooks. It only renders you a navigation bar component according to Apple guidelines (although it works for Android as well). If you want navigation +/ animations, you may consider using, ex-navigator, navigation-experimental, navigator, navigator-ios, navigator-redux or any other solution for routing.

**Comment by janroures** [comment]
Thank you, I figured. What I'm asking is, is there any way to get rid of this "white background" behind the navbar in both push and pop transitions (or keep the navbar fixed to the top)?

**Comment by Kureev** [comment]
I'm not sure I understand what you mean by "white background" behind a navbar. Can you attach a screenshot please?
