### ISSUE TITLE
custom title is not vertical center

### ISSUE THREAD

**Issue by yezongyang** [react-native-community/react-native-navbar#197]
customTitle: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 7,
    alignItems: 'center',
  }

**Comment by Kureev** [comment]
But you can supply a custom style to your custom component, right?

Sorry, but I'm about to close this issue because it doesn't sound like something actionable.

**Comment by yezongyang** [comment]
customTitle: {
position: 'absolute',
left: 0,
right: 0,
bottom: 0,
right:0,
justifyContent: 'center'
alignItems: 'center
}


add two line style can fix this

**Comment by Kureev** [comment]
This component also covers a status bar, i.e. +20 pixels from top (at least on iOS). If we make it `top: 0, bottom: 0`, then it'll overlap the status bar.

**Comment by yezongyang** [comment]
oh, i got it. so i have to supply a custom style.

**Comment by JaxGit** [comment]
Running v1.6.0 which released on Dec 29, 2016, and a customTitle element won't cover status bar by applying styles.navBarTitleContainer instead of styles.customTitle.
Guess it's safe to discard hacky customTitle style now?
