### ISSUE TITLE
install react-native-navbar

### ISSUE THREAD

**Issue by cyaxares** [react-native-community/react-native-navbar#204]
I installed react-native-navbar, But while using showed error like pic:

![navbar3](https://cloud.githubusercontent.com/assets/9538639/23165726/c8df3d78-f852-11e6-979a-4ccb1e47695a.png)
I checked and It existed before , I also removed it and installed by npm

Code:
```
'use strict';

import React, { Component } from 'react';
import{
  View,
  Text,
  StyleSheet

} from 'react-native';
import NavigationBar from 'react-native-navbar';

class Header extends Component {
    render() {
      const rightButtonConfig = {
        title: 'Next',
        handler: () => alert('hello!')
      };
      const titleConfig = {
        title: 'Hello, world',
      };

      return (
        <View>
          <NavigationBar
            title={titleConfig}
            rightButton={rightButtonConfig} />
        </View>
      );
    }
}
export default Header;

```
what's the problem?

**Comment by Kureev** [comment]
Most likely your packager needs a restart. Try to shut down your packager process and restart the app.

**Comment by cyaxares** [comment]
What do u mean by "packager"? npm or react-native?

**Comment by Kureev** [comment]
At the moment when you start react-native application, xcode (or react-native run-ios/android script) starts a packager - CLI tool that makes a JS bundle that runs on your simulator/device. Usually, it opens in a new terminal window and looks like this:
![image](https://cloud.githubusercontent.com/assets/2273613/23203503/10e9bfea-f8e3-11e6-9a0c-8530f90bfac6.png)

**Comment by Kureev** [comment]
Did you manage to solve your issue? If so, can you please tell us what helped and close this one?

**Comment by cyaxares** [comment]
Yes, i do install nativebase.

Thanks
