### ISSUE TITLE
change font size for left/right Button

### ISSUE THREAD

**Issue by applechips** [react-native-community/react-native-navbar#205]
does anyone know how to change the font size for the left/right buttons?

i can change the fontSize in the title, but not anywhere else. i'm trying to make the left/right button text smaller than the title.

i tried to pass fontSize like this:
```
  const rightButtonConfig1 = {
      title: 'Save',
      tintColor: 'white',
      style: {
        borderWidth: 2,
        borderRadius: 5,
        borderColor: '#00C0A9',
        backgroundColor: '#00C0A9',
        borderLeftWidth: 10,
        borderRightWidth: 10,
        borderTopWidth: 5,
        borderBottomWidth: 3,
        fontSize: 10,
      },
      handler: () => this.navigate('topic1'),
    };
```

but i get this error: 
![simulator screen shot feb 22 2017 5 22 01 pm](https://cloud.githubusercontent.com/assets/20119077/23240690/a480bf98-f923-11e6-8a3a-90966115d2c0.png)

it doesn't seem like i can pass any property related to font. any idea of how to fix this?

**Comment by Kureev** [comment]
Hi @applechips! Sorry for the first misleading answer on twitter. You can configure only a view properties (container for the button) using style. To adjust font size etc, you'll have to pass your own components as button(s).

**Comment by applechips** [comment]
@Kureev ah, no worries -  thank you!! do you happen to have a simple example? i wouldn't know where to put it. I tried to put it in between the `NavigationBar` tags like this:
```
<NavigationBar> 
    <Button /> 
</NavigationBar>
```
but nothing appears when i put it inside the tag. sorry for the trouble!

**Comment by Kureev** [comment]
Sure! There is an `examples` folder in the repo. In particular, I think you need to take a look on code in [CustomElements](https://github.com/react-native-community/react-native-navbar/tree/master/examples/CustomElements) project.

**Comment by Kureev** [comment]
I believe this one is solved and can be closed. Feel free to ping me if you need any other input from me about this (so I'll re-open it).
