### ISSUE TITLE
Have multiple buttons

### ISSUE THREAD

**Issue by vaderdan** [react-native-community/react-native-navbar#206]
Hi
Is it possible to add multiple buttons on the right side
like 
`<NavigationBar
        title={{title: 'hello'}}
        rightButton={[{title: 'next'}, {title: 'next'}]}`

**Comment by Kureev** [comment]
Hi,

Not like this, but you can supply a custom component to the rightButton that contains buttons you want:

```jsx
function RightButton(props) {
  return (
    <View>
      <Button1 />
      <Button2 />
    </View>
  );
}
```

**Comment by vaderdan** [comment]
thanks!
