### ISSUE TITLE
Warning: React.createElement: type is invalid -- expected a string 

### ISSUE THREAD

**Issue by linoleum00** [react-native-community/react-native-navbar#212]
I just updated my app to RN 0.42, and react-native-navbar from 1.5.1 to 1.6.3 and it is not working, I'm getting this warning:

2017-03-14 16:12:03.834 [warn][tid:com.facebook.react.JavaScript] Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Navigator`.

![simulator screen shot mar 14 2017 4 17 45 pm](https://cloud.githubusercontent.com/assets/3660845/23922800/cc928666-08d1-11e7-810c-129f445c0f53.png)

but with this warning my screen is blank, nothing is rendered, and if I remove the NavigationBar component then my screen is rendered.

Please help me with this! Thanks

**Comment by Kureev** [comment]
Hi @linoleum00,

Can you please provide some code?

**Comment by z-hao-wang** [comment]
see https://github.com/react-native-community/react-native-navbar/pull/213

**Comment by linoleum00** [comment]
Thanks to @z-hao-wang 's PR, @Kureev just gave me the solution for this.
I was using require to get the library because of some logic I don't even remember why we did it that way. I just change that to import and now it is working
