### ISSUE TITLE
Tapping two buttons at once

### ISSUE THREAD

**Issue by mini-eggs** [react-native-community/react-native-navbar#219]
"react": "~15.4.1",
"react-native": "0.42.3"

I have a number of `TouchableHighlight`'s on a scene. I would like users to be able to tap two or more at the same time. Is this possible and if so can someone point me towards a resource on how to do this? Searching hasn't given me any luck.

Thank you for your time.

**Comment by Kureev** [comment]
As for me, it's a pretty strange case. Can you find any resource explaining something similar in iOS/Android world? I think you'll end up creating something pretty custom.

**Comment by mini-eggs** [comment]
Note: this has been closed due to not being opened in the most pertinent repo and reworking multiple TouchableHighlights with a PanResponder will resolve this.
