### ISSUE TITLE
Custom icon font

### ISSUE THREAD

**Issue by itswaze** [react-native-community/react-native-navbar#220]
Hi!
Is it possible to use custom fonts? When I try to add mine, for example:

```
          left={{
              icon: "back",
              iconColor: "#838383",
              label: "Back",
              style:{color: '#838383', fontSize: 13, fontFamily: 'rubik-regular'},
              onPress: () => Actions.stock()
            }}
```

I get the character "?" on the icon. But it works on the rest of the app, only on the Navbar it's not working.
Doing something wrong?

**Comment by Kureev** [comment]
We're not doing anything specific about button styles. These styles are just passed to the underlying component, nothing else. It's less likely that this issue is caused by this library.

**Comment by itswaze** [comment]
Don't really know what I am doing it wrong... I get the error saying it is expecting other names (from IonIcons) but Im calling my own custom font, and I even imported corretly.

It works fine on other stuff, only not working on the NavBar.
