### ISSUE TITLE
Undefined is not an object (evaluating '_react.Proptypes.oneOfType')

### ISSUE THREAD

**Issue by justuseapen** [react-native-community/react-native-navbar#225]
context:

Brand new react native project. I've never spun up a RN project from scratch before (worked on existing projects though) Here's the package.json:
`{
	"name": "testDashboardApp",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"flow": "flow",
		"test": "jest"
	},
	"dependencies": {
		"react": "^16.0.0-alpha.12",
		"react-native": "^0.45.1",
		"react-native-bottom-navigation": "^0.1.5",
		"react-native-navbar": "^1.7.1"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "2.0.0",
		"flow-bin": "0.33.0",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}
`

Any idea what's causing this?

![image](https://user-images.githubusercontent.com/4587141/27742660-7d718126-5d87-11e7-9666-96200d107183.png)

**Comment by Kureev** [comment]
Hi @justuseapen!

Sorry for the late response. I just merged in https://github.com/react-native-community/react-native-navbar/pull/227, so it should be fixed in the upcoming release
