### ISSUE TITLE
Deprecated view.proptypes

### ISSUE THREAD

**Issue by RameshkrishnanV** [react-native-community/react-native-navbar#230]
Hi i got this error can u please check on this...

Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.

**Comment by Kureev** [comment]
Hi @RameshkrishnanV!

Thanks for reporting this issue. Would you like to send a PR?

**Comment by Kureev** [comment]
Sorry, there was a PR for this already :)
