### ISSUE TITLE
What version of react-native is required?

### ISSUE THREAD

**Issue by gtzogana** [react-native-community/react-native-navbar#231]
What is the earliest version of `react-native` compatible with this component?
I'm wondering because I'm getting `cannot read property _style_ of undefined` on `ViewPropTypes.style` in react-native 0.39.2.

**Comment by Kureev** [comment]
I believe 1.8.0 should be good for you

**Comment by qiangspecial** [comment]
`ViewPropTypes` is support in react-native@^0.44

**Comment by Kureev** [comment]
Sorry, I've unpublished 1.8.1 (which should've been 2.0.0), so version < 2.0 is compatibly with old RN and >= 2.0 with 0.44+

**Comment by iRoachie** [comment]
@Kureev I'll send in a PR that allows both versions to work

**Comment by iRoachie** [comment]
@gtzogana I've sent the fix and it's been merged. You can use the latest version of react-native-navbar (2.0.1) with your current version of react-native
