### ISSUE TITLE
Put image instead of title

### ISSUE THREAD

**Issue by munkhorgil** [react-native-community/react-native-navbar#235]
How to put image instead of title ?

`var img = {
      render() {
        return <Image source={require('../images/logo.png')} />;
      }
    };
`

`<NavigationBar
          title={img}
          statusBar={statusBar}
          style={styles.navbarContainer}
  />
`

**Failed prop type: Invalid prop title**

**Comment by Kureev** [comment]
I'm afraid you can't use plain objects as React components. 
Consider using `class TitleComponent extends React.Component { render() { ... } }` instead.

**Comment by munkhorgil** [comment]
What about using StackNavigator ?

**Comment by Kureev** [comment]
What about it? How is it related to the topic?

**Comment by Luckygirlllll** [comment]
@Kureev @munkhorgil I also want to add image instead of the title in the app, is that possible to do that using this library?

**Comment by Kureev** [comment]
👋 @Luckygirlllll!

Sure, you can pass ReactElement to `title` property of `react-native-navbar`:

```js
<Navbar title={<Image source={...}} />
```

**Comment by Luckygirlllll** [comment]
@Kureev Is that possible to add text and image for the title?
