### ISSUE TITLE
iphoneX additional padding? 

### ISSUE THREAD

**Issue by hkung77** [react-native-community/react-native-navbar#236]
I find the status bar on iphoneX is covering the buttons on the top. I'm wondering if it's better to add some kind of support here? Or I'll just do it manually?

**Comment by Kureev** [comment]
Hi @hkung77! Would be nice to add some kind of support here. I need to take a look on Apple Design guidelines 🤔

**Comment by nodkrot** [comment]
Any update on this?

**Comment by AustinErck** [comment]
Updates?

**Comment by AlexanderCollins** [comment]
I’ve been using react-native SafeAreaView as a wrapper. I have an iPhoneX and it works well.

Import {SafeAreaView} from ‘react-native’
