### ISSUE TITLE
Drag back handle

### ISSUE THREAD

**Issue by janroures** [react-native-community/react-native-navbar#237]
Hello, is there any way to detect the 'drag back' event of the navBar? Thank you.

**Comment by Kureev** [comment]
What is a "drag back" event? Can you give us more info? What exactly you're trying to achieve?

**Comment by janroures** [comment]
sorry, what I mean is, instead of popping a component programatically, when you slide the component from left to right to go back, mimicking the native iOS back movement. Hope this makes sense

**Comment by Kureev** [comment]
Sure it does! It is a standard iOS ViewController behavior which should be implemented on the side of navigation library, not navbar component. Take a look at react-navigation, I believe that’s what you are looking for 👍

**Comment by janroures** [comment]
what about Android? Same behavior and I don't think they implemented that on the native navigator. Don't know.

**Comment by Kureev** [comment]
Probably they didn't (not sure though). Anyway, it isn't a standard pattern on Android, so if you need it, most likely you'll end up implementing it by yourself.

However, this is no longer a navbar issue. Please, consider asking your question on Discord channel and/or StackOverflow.

**Comment by janroures** [comment]
Oh I'm sorry, I guess I didn't explain myself well. What I mean is, this feature is implemented in your library somewhere, but I can't find the piece of code where it is located.
