### ISSUE TITLE
App Exits without showing any error

### ISSUE THREAD

**Issue by skathayat** [react-native-community/react-native-navbar#239]
With react@16, react-native 0.49+

react-native-navbar is causing problem when app is uploaded to TestFlight and download to a device.
The app exits right after launch screen without throwing any error message. In my app´s first screen, react-native-navbar is imported. When react-native-navbar is not imported in a javascript file, the app starts with the upload (to TestFlight) and download (to Device).

My app just works fine the app is directly deployed to device, for example from Xcode.

Have someone experienced this? or Any clues?

Regards
Surya

**Comment by skathayat** [comment]
I found out why that was happening! Even 1.8 version of `react-native-navbar` uses View.PropTypes (probably no longer supported by latest react-native!) instead of ViewPropTypes. So, would be great it can be patched up!

**Comment by Kureev** [comment]
Hi @skathayat!

I think it was fixed quite some time ago in one of the latest versions (current version 2.1.0)
